### ISSUE TITLE
Infinit loading then running template

### ISSUE THREAD

**Issue by nzxt** [cesaramirez/nuxt-starter#1]
Hi! Trying to use your template, but after
```
git clone
npm i
npm run dev
```
i'm seeing only nuxt.js ripple dot in the center of my screen. This nuxt loading is infinit. And only warnings that vendor.js is more then 300kb i can find in console.
Can you tell me where to dig?

> node.js - v8.7.0
> npm - v5.6.0
> yarn - v1.3.2

**Comment by cesaramirez** [comment]
I reproduced the same steps and it seems that there is a problem installing it with NPM.

Please try with yarn:

```bash
yarn
```
```bash
yarn dev
```

**Comment by nzxt** [comment]
Today then i'm doing same things - all is ok! In Chrome & FF, with Yarn & NPM. Seems like it was an temporary browser's problem. Thanks, keep your template up-to-date.
